# Disabled due to https://github.com/zmkfirmware/zmk/issues/2556
# Implement 1 wakeup source from GPIO as workarround
#
# Milliseconds of inactivity before entering deep sleep
# 900000ms (15 minutes)
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
#
# Enable deep sleep support
# CONFIG_ZMK_SLEEP=y 

# Keyboard Name
CONFIG_ZMK_KEYBOARD_NAME="Caon"

# SPI Enable
CONFIG_SPI=y

# Milliseconds of inactivity before entering idle state
# 30000ms (30 seconds)
CONFIG_ZMK_IDLE_TIMEOUT=30000

# Delay in ms between matrix row is activated and when the columns are read 
CONFIG_ZMK_KSCAN_MATRIX_WAIT_BEFORE_INPUTS=25
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# Encoders Enable
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Pointing Device/Mouse Emulation Enable
CONFIG_ZMK_POINTING=y

# Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# NICE OLED General Config
## WIDGETS
CONFIG_NICE_OLED_WIDGET_WPM=y
CONFIG_NICE_OLED_WIDGET_WPM_NUMBER=y
CONFIG_NICE_OLED_WIDGET_WPM_SPEEDOMETER=y
CONFIG_NICE_OLED_WIDGET_WPM_GRAPH=y
CONFIG_NICE_OLED_WIDGET_WPM_GRAPH_FIXED_RANGE=y
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS=n
CONFIG_NICE_OLED_WIDGET_WPM_LUNA=n
CONFIG_NICE_OLED_WIDGET_RESPONSIVE=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT=n

## SYMBOL
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED_SYMBOL_MACOS=n
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED_SYMBOL_WINDOWS=y
