# Keyboard Name
CONFIG_ZMK_KEYBOARD_NAME="Caon"

# SPI Enable
CONFIG_SPI=y

# Enable deep sleep support
CONFIG_ZMK_SLEEP=y

# Milliseconds of inactivity before entering idle state
# 30000ms (30 seconds)
CONFIG_ZMK_IDLE_TIMEOUT=30000

# Milliseconds of inactivity before entering deep sleep
# 900000ms (15 minutes)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Delay in ms between matrix row is activated and when the columns are read 
CONFIG_ZMK_KSCAN_MATRIX_WAIT_BEFORE_INPUTS=25
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# Encoders Enable
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Pointing Device/Mouse Emulation Enable
CONFIG_ZMK_POINTING=y

# Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# NICE OLED Config
## Set to n to disable slave animation
CONFIG_NICE_OLED_GEM_ANIMATION=y
## 2x slower, 30fps
CONFIG_NICE_OLED_GEM_ANIMATION_MS=1920

## set max to 150
CONFIG_NICE_OLED_GEM_WPM_FIXED_RANGE_MAX=150

## LUNA Disable
CONFIG_NICE_OLED_WIDGET_WPM=n
CONFIG_NICE_OLED_WIDGET_WPM_LUNA=n
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS=n
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS_LUNA=n
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS=n
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_LUNA=n