# SPI Enable
CONFIG_SPI=y

# Delay in ms between matrix row is activated and when the columns are read 
CONFIG_ZMK_KSCAN_MATRIX_WAIT_BEFORE_INPUTS=25
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

CONFIG_ZMK_KEYBOARD_NAME="Caon"

# Encoders Enable
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y